name: Node.JS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [10, 12, 14, 16]
        test_framework: [jasmine@2, jasmine@3, jest@25, jest@latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Install ${{ matrix.test_framework }}
        run: |
          npm install ${{ matrix.test_framework }}

      - name: Install jest-circus@25
        if: ${{ matrix.test_framework == 'jest@25' }}
        run: |
          npm install jest-circus@25

      - name: Install jest-circus@latest
        if: ${{ matrix.test_framework == 'jest@latest' }}
        run: |
          npm install jest-circus@latest

      - name: Run unit tests
        run: |
          npm run test:unit

      - name: Run jasmine tests
        if:
          ${{ matrix.test_framework == 'jasmine@2' || matrix.test_framework == 'jasmine@3' }}
        run: |
          npm run test:jasmine

      - name: Run jest-jasmine tests
        if:
          ${{ matrix.test_framework == 'jest@25' || matrix.test_framework == 'jest@latest' }}
        run: |
          npm run test:jest-jasmine2

      - name: Run jest-circus tests
        if:
          ${{ matrix.test_framework == 'jest@25' || matrix.test_framework == 'jest@latest' }}
        run: |
          npm run test:jest-circus
