name: Node.JS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [12, 14, 16, 18]
        test_framework: [jasmine@2, jasmine@latest, jest@25, jest@latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Install ${{ matrix.test_framework }}
        run: |
          npm install ${{ matrix.test_framework }}

      - name: Install jest@25 deps
        if: ${{ matrix.test_framework == 'jest@25' }}
        run: |
          npm install jest-circus@25
          npm install jest-environment-jsdom@25
          npm install jest-environment-node@25

      - name: Run unit tests
        run: |
          npm run test:unit

      - name: Run jasmine tests
        if:
          ${{ startsWith(matrix.test_framework, 'jasmine') }}
        run: |
          npm run test:jasmine

      - name: Run jest-jasmine tests
        if:
          ${{ startsWith(matrix.test_framework, 'jest') }}
        run: |
          npm run test:jest-jasmine2

      - name: Run jest-circus tests
        if:
          ${{ startsWith(matrix.test_framework, 'jest') }}
        run: |
          npm run test:jest-circus
